name: Build and Release

on:
  push:
    tags:
      - 'v*'   # Runs only when you push a tag like v0.2.2

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build React frontend
        run: npm run build

      - name: Package Electron app
        run: npx electron-builder --${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'win' || 'mac' }} --publish never

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: release/**/*   # Upload everything electron-builder generated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
